#
# MAIN
#

- name: Pre-Requesites
  include: pre_requesites.yml

- name: Fetch new data
  setup:

- name: Get the instance EC2 info
  action: ec2_facts
  register: ec2_data

- name: Common tasks
  include: common.yml

- name: Global configuration
  include: global_configuration.yml

- name: EIP
  include: get_addresses.yml

- name: Add ansible logrotate
  copy: src=ansible dest=/etc/logrotate.d/ansible
